registry: ${DOCKER_REGISTRY}

imageTag: ${BUILD_VERSION}
imagePullPolicy: IfNotPresent

replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi