version: '3.3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - $MYSQL_PORT:$MYSQL_PORT             # <Port exposed> : < MySQL Port running inside container>
    volumes:
      - my-db:/var/lib/mysql    # Where our data will be persisted
registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  volumes:
    - /path/data:/var/lib/registry
    - /path/certs:/certs
    - /path/auth:/auth
volumes:
  my-db: