// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

// User defines model for User.
type User struct {
	Password   string `json:"password"`
	Privileges int    `json:"privileges"`
	Username   string `json:"username"`
}

// PostUserJSONBody defines parameters for PostUser.
type PostUserJSONBody = User

// PostUserJSONRequestBody defines body for PostUser for application/json ContentType.
type PostUserJSONRequestBody = PostUserJSONBody
