// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

// User defines model for User.
type User struct {
	Id         int    `json:"id"`
	Password   string `json:"password"`
	Privileges int    `json:"privileges"`
	Username   string `json:"username"`
}

// PostUsersJSONBody defines parameters for PostUsers.
type PostUsersJSONBody = User

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = PostUsersJSONBody
