// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6RUTW/bMAz9K4S2wwYEdrr1sty6FtjSrWuxNKeiB8WiY3W2pFF00qDwfx8k16kdp0CB",
	"nSzw45HvkfSTyGzlrEHDXsyehM8KrGR8Lj1S+DqyDok1RquT3m8tqfDGR1m5EsVsbz0RE8E7F0yeSZu1",
	"aCbCkd7oEtctwD5pug/VhnGNFGJrj2RkhUP4S1sYWFSaizF+MxGEf2tNqMTsTmgleiiTl34HfdzvYezq",
	"ATMWTcDRJrehsEKfkXasrREzsYhdwJnTobjm2FFnvJmLidgg+TZ2mpwkXwIP69BIp8VMfE6myTQ2wkUU",
	"IPUsuY7PNfK43jdkeA6JOCSDY65a16LzEHpnjW9F/TSdjoGuf0R1fF1VknZD5OBI627C1sc+hsVurOe4",
	"A63A6PmrVbsQl1nDaGKKdK7UWUxKH3wo2+1QeL0nzMVMvEtflix93rA0QjfD8THV2IyonYypnRNKRnXA",
	"r7V6kBCYJS8kXxf7Oj5kCfjIaBQq6PlBGzi3VWXNlaQ/YAm+3179TI6NZRmrHJ/Km+XSjFVMHJ3Qs0ES",
	"yV0r2pDGGVwurn9B9IPNI38IF+APJPqNXJMJEpXacxfq1aqvVvrUHVDTE+4452X/1EhWyFHuu0Ohu7h9",
	"d1xIhi3CVhoGtpAjZ0XQVpv4Q4m33v4K+vc8XJZJT73D/8L9f07jbcs7PrmJOD12jbcFgneY6VyjaiWY",
	"X4D2oM1GllrBB2MZJJi6WiF9TFqg0zHQWZu81VwAD0DnF7CVHgJObmujIobCXNblkdVfGnx0mDEqQCJL",
	"r25KLLfawfwiaTl7pE035ZpKMROpaO6bfwEAAP//m+Hr90wGAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
