name: Go package

on: [push]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASS: ${{secrets.DOCKER_PASS}}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Go
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Lint
        run: make lint

      - name: Test
        run: make unit-tests

      - name: Build
        run: make docker-build-debug

      - name: Publish
        run: make docker-push-debug